### ISSUE TITLE
2016-11-28 15:06:01.921 [main] ERROR o.s.boot.SpringApplication - Application startup failed java.lang.NoSuchMethodError: org.springframework.messaging.handler.annotation.support.MessageMethodArgumentResolver.<init>(Lorg/springframework/messaging/converter/MessageConverter;)V

### ISSUE THREAD

**Issue by RobinsChens** [code-not-found/spring-kafka#1]
2016-11-28 15:06:01.921 [main] ERROR o.s.boot.SpringApplication - Application startup failed
java.lang.NoSuchMethodError: org.springframework.messaging.handler.annotation.support.MessageMethodArgumentResolver.<init>(Lorg/springframework/messaging/converter/MessageConverter;)V

**Comment by code-not-found** [comment]
Hi, could you give a bit more information about when you encounter the error?

**Comment by code-not-found** [comment]
Closing issue.

**Comment by Cs4r** [comment]
@code-not-found why did you close the issue? What's the fix?

**Comment by code-not-found** [comment]
@Cs4r I never got any additional information on the details of the above error. In addition I have added a Travis job that tests all example projects using an embedded broker.
